<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBooks-MacBook-Pro.local" failures="1" tests="2" name="Test1" time="31.9" errors="0" timestamp="2022-01-12T12:17:51 GMT">
  <testcase classname="tests.LoginTest" name="login" time="3.377">
    <failure type="java.lang.AssertionError" message="expected [Success1] but found [Success]">
      <![CDATA[java.lang.AssertionError: expected [Success1] but found [Success]
at tests.LoginTest.login(LoginTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.LoginTest" name="login" time="13.224"/>
</testsuite> <!-- Test1 -->
